React capstone project
Elijahdre/metrics-webapp pull request #1
Opened 2022-10-07 17:50 UTC by Elijahdre

# Crypto metrics webapp

- [ ] The project is a single-page application (SPA) built with React and Redux.
- [ ] The data retrieved from the API should be stored in the Redux store.
- [ ] You should filter the data that you retrieve from the API using a Filter stateless component.
- [ ] Every page (the main page and the pages for each item) should have a unique route within the SPA.
- [ ] The project should be deployed and accessible online (add a link to the online version of your app to your README file).
- [ ] link to [video](https://www.loom.com/share/87092be77bf942c795edf7436ef9f588)

2022-10-07 18:22 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Elijahdre👋, 

### You are doing a marvelous job on the React capstone project and this is one of the best projects I have seen so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️
- All tests are passed. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-07 18:22 UTC, thecodechaser commented on src/components/Homepage.js
> +
- [ ] You did really a great job on this project but you missed a major requirement. Please add a feature on the home page to filter cryptos. (You should include a search feature on the page).
![image](https://user-images.githubusercontent.com/83803414/193900059-ae0b963d-7671-4e1c-910c-bc3ad366aaa2.png)

2022-10-07 18:22 UTC, thecodechaser commented on README.md
> +- [x] Here is the presentation video [link]()👈
- [ ] Please make sure to show(highlight) some interesting piece of code or something you built that you are very proud of in the presentation video as requested in the project requirements. (You may want to record the video again with highlighted code).

2022-10-07 18:22 UTC, thecodechaser commented on README.md
> +Screenshots can be found in the repository.
- [ ] The mockup and screenshots are broken in the README file, Please make sure to fix this issue.

2022-10-07 18:22 UTC, thecodechaser commented on README.md
> +
- [ ] The live version of the application is broken in the README file, Please make sure the project should be deployed and accessible online also add deployed link in the README file.

2022-10-07 22:56 UTC, Elijahdre commented on src/components/Homepage.js
> +
@thecodechaser  Thank you for the review. This is just a project description. If you can check the technical requirement which I paid the most attention to, that feature was not included also on the project screenshot.

2022-10-08 00:32 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @Elijahdre 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-08 00:32 UTC, tresorsawasawa commented on src/components/Homepage.js
> +}
- [ ] As mentioned by the previous reviewer and for the project requirements, kindly make sure your **Home Page** has a list of categories that could be filtered using given parameters, **e.g. category name**. I suggest you add a search bar so you can type the name of the crypto you need and get it from the list.

2022-10-08 00:32 UTC, tresorsawasawa commented on src/components/Homepage.js
> +
Hi @Elijahdre. I think if you correctly check the requirements for the Home page you will find that there is a comment telling what the review said.

2022-10-08 00:33 UTC, tresorsawasawa commented on src/components/Homepage.js
> +
Hi @Elijahdre. I think if you correctly check the requirements for the Home page you will find that there is a comment telling what the reviewer said.

2022-10-08 00:49 UTC, Elijahdre commented on src/components/Homepage.js
> +}
@tresorsawasawa 
![cr](https://user-images.githubusercontent.com/47558964/194679073-08511b9f-4560-4a18-b699-b43526934ca9.png)
Thank you but I don't see a search option on the technical requirements. Many other projects have been approved and they didn't have that too. My partner's was approved.

2022-10-08 00:57 UTC, tresorsawasawa commented on src/components/Homepage.js
> +}
Hi @Elijahdre 

Adding the **search option** is a suggestion to help you match the requirement saying that: **"The Home Page has a list of categories that could be filtered using given parameters, e.g. category name"**
![Screenshot from 2022-10-08 02-53-02](https://user-images.githubusercontent.com/83042742/194679452-b08fb18b-46cc-4563-9c7a-664d6c719aa4.png)

2022-10-08 01:11 UTC, Reem-lab requested changes
# Hi @Elijahdre, 👋🏻👋🏻 

Great work on making the changes requested by a previous reviewer 👏 💪🏻💪🏻🔥🔥
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media2.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>


 ## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the functionality and design✅
📌 Good commit messages ✅
📌 Professional README ✅

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-08 15:16 UTC, medaminedev66 approved these changes
Hi @Elijahdre 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 💯 
Congratulations! 🎉 

### Highlights
- Your project works as expected and runs without errors.
- The feature of filtering the data has been implemented.
- Your repo looks professional.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 07:47 UTC, merged

2023-01-15 09:43 UTC, Elijahdre commented
@medaminedev66 Thank you for the review.

2023-01-15 09:44 UTC, Elijahdre commented on src/components/Homepage.js
> +}
@tresorsawasawa Yes it is clear. Thank you